PROGRAM := main
STRUCPP ?= ../../../../../strucpp
ECMC_PLUGIN_STRUCPP ?= ../../../..
STRUCPP_CLI := strucpp -L $(ECMC_PLUGIN_STRUCPP)/libs
include $(ECMC_PLUGIN_STRUCPP)/templates/strucpp_ioc_logic.make
