PROGRAM := main
ANNOTATION_DEFINES := CH_ID=01
INCLUDE_MOTION_ST := 1
STRUCPP ?= ../../../../../strucpp
ECMC_PLUGIN_STRUCPP ?= ../../../..
include $(ECMC_PLUGIN_STRUCPP)/templates/strucpp_ioc_logic.make
