#!/usr/bin/env python3

import argparse
import pathlib
import sys


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate dedicated IOC-level <IOC>_strucpp.subs from app substitutions."
    )
    parser.add_argument("--output", required=True, help="Output <IOC>_strucpp.subs file")
    parser.add_argument("--ioc-name", required=True, help="Concrete IOC name to embed in the substitutions file")
    parser.add_argument(
        "--input",
        action="append",
        default=[],
        help="Input substitutions file to merge. Can be repeated.",
    )
    parser.add_argument(
        "--prefix",
        default=None,
        help="Literal PV prefix to inject into substitutions, default <ioc-name>:",
    )
    parser.add_argument(
        "--port",
        default="PLUGIN.STRUCPP0",
        help="Literal asyn port name to inject, default PLUGIN.STRUCPP0",
    )
    return parser.parse_args()


def normalize_substitutions(text: str, prefix: str, port: str):
    return text.replace("$(P=)", prefix).replace("$(PORT=PLUGIN.STRUCPP0)", port)


def main():
    args = parse_args()
    output_path = pathlib.Path(args.output)
    input_paths = [pathlib.Path(value) for value in args.input]
    prefix = args.prefix if args.prefix is not None else f"{args.ioc_name}:"

    lines = [
        "# Auto-generated by strucpp_ioc_subsgen.py",
        "# This file is intended to be auto-loaded by the IOC infrastructure.",
        "",
        f'global {{ IOC = "{args.ioc_name}" }}',
        "",
    ]

    first = True
    for input_path in input_paths:
        if not input_path.exists():
            raise RuntimeError(f"Missing substitutions input: {input_path}")
        text = normalize_substitutions(
            input_path.read_text(encoding="utf-8"),
            prefix,
            args.port,
        ).strip()
        if not text:
            continue
        if not first:
            lines.append("")
        first = False
        lines.append(f"# Begin {input_path.name}")
        lines.append(text)
        lines.append(f"# End {input_path.name}")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    try:
        main()
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
