#!/usr/bin/env python3

import argparse
import pathlib
import re
import sys


def normalize_ioc_name(raw: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "-", raw.strip()).strip("-")
    return cleaned.upper() or "STRUCPP-IOC"


def parse_args():
    script_path = pathlib.Path(__file__).resolve()
    plugin_root = script_path.parent.parent
    default_strucpp = plugin_root.parent / "strucpp"

    parser = argparse.ArgumentParser(
        description="Scaffold a minimal IOC project for ecmc_plugin_strucpp."
    )
    parser.add_argument("output_dir", help="Directory to create")
    parser.add_argument(
        "--ioc-name",
        help="IOC name used for startup/parameter filenames, default derived from output dir",
    )
    parser.add_argument(
        "--program",
        default="main",
        help="ST program filename stem, default: main",
    )
    parser.add_argument(
        "--logic-name",
        default="main",
        help="Built logic library stem, default: main",
    )
    parser.add_argument(
        "--slave",
        default="14",
        help="EtherCAT slave number for the direct mapping example, default: 14",
    )
    parser.add_argument(
        "--plugin-root",
        default=str(plugin_root),
        help="Path to ecmc_plugin_strucpp, default: this script's repo root",
    )
    parser.add_argument(
        "--strucpp-root",
        default=str(default_strucpp),
        help="Path to strucpp checkout, default: sibling ../strucpp",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow writing into an existing non-empty directory",
    )
    return parser.parse_args()


def render(template: str, mapping: dict) -> str:
    rendered = template
    for key, value in mapping.items():
        rendered = rendered.replace(f"@{key}@", value)
    return rendered


TOP_MAKEFILE = """all:
\t$(MAKE) -C src stage

install: all
\tioc install --source .
"""


STARTUP_SCRIPT = """# Generated by strucpp_new_ioc.py.
# This sample expects direct EL7041 PDO items:
#   %IW0 -> ec0.s@SLAVE@.positionActual01
#   %QW0 -> ec0.s@SLAVE@.driveControl01
#   %QW2 -> ec0.s@SLAVE@.velocitySetpoint01

epicsEnvSet(STRUCPP_LOGIC_LIB,"bin/@LOGIC_NAME@.so")

require ecmc_plugin_strucpp sandst_a "LOGIC_LIB=${STRUCPP_LOGIC_LIB}"
"""


PARAMETERS_YAML = """ioc_name: @IOC_NAME@
ioc_host: example-softioc-01
interpreter: iocsh
epics_version: 3.14.12
os: RHEL7
os_id: rhel
cpu_architecture: x86_64
"""


IOC_README = """# `@DIRNAME@`

Generated by `strucpp_new_ioc.py` as a minimal `ecmc_plugin_strucpp` IOC
project.

This scaffold is intentionally small:

- one ST source file: [`src/@PROGRAM@.st`](src/@PROGRAM@.st)
- one short makefile: [`src/Makefile`](src/Makefile)
- no handwritten C++ sources
- startup only passes `LOGIC_LIB`

The expected flow is:

1. `make`
2. `ioc install --source .`
3. start the IOC

The startup script expects the generated runtime artifacts in `bin/`:

- `bin/@LOGIC_NAME@.so`
- `bin/@LOGIC_NAME@.so.map`
- `bin/@LOGIC_NAME@.so.substitutions`

This sample uses direct EL7041 item mapping:

- `%IW0` -> `ec0.s@SLAVE@.positionActual01`
- `%QW0` -> `ec0.s@SLAVE@.driveControl01`
- `%QW2` -> `ec0.s@SLAVE@.velocitySetpoint01`
"""


SRC_MAKEFILE = """PROGRAM := @PROGRAM@
LOGIC_NAME := @LOGIC_NAME@
ECMC_PLUGIN_STRUCPP ?= @PLUGIN_ROOT@
STRUCPP ?= @STRUCPP_ROOT@
include $(ECMC_PLUGIN_STRUCPP)/templates/strucpp_ioc_logic.make
"""


ST_SOURCE = """PROGRAM MAIN
VAR
  actual_position    AT %IW0 : INT;   // @ecmc ec0.s@SLAVE@.positionActual01
  drive_control      AT %QW0 : WORD;  // @ecmc ec0.s@SLAVE@.driveControl01
  velocity_setpoint  AT %QW2 : INT;   // @ecmc ec0.s@SLAVE@.velocitySetpoint01
  cycle_counter      AT %MW0 : INT;   // @epics plugin.strucpp.main.cycle_counter
  actual_pos_export           : INT;   // @epics plugin.strucpp.main.actual_position
END_VAR

actual_pos_export := actual_position;
cycle_counter := cycle_counter + 1;
drive_control := 16#0001;

IF actual_position < 1000 THEN
  velocity_setpoint := 1000;
ELSE
  velocity_setpoint := -1000;
END_IF;
END_PROGRAM
"""


def write_text(path: pathlib.Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main():
    args = parse_args()
    output_dir = pathlib.Path(args.output_dir).resolve()
    if output_dir.exists() and any(output_dir.iterdir()) and not args.force:
        raise RuntimeError(
            f"{output_dir} already exists and is not empty; rerun with --force to overwrite files"
        )

    ioc_name = normalize_ioc_name(args.ioc_name or output_dir.name)
    mapping = {
        "DIRNAME": output_dir.name,
        "IOC_NAME": ioc_name,
        "PROGRAM": args.program,
        "LOGIC_NAME": args.logic_name,
        "PLUGIN_ROOT": str(pathlib.Path(args.plugin_root).resolve()),
        "STRUCPP_ROOT": str(pathlib.Path(args.strucpp_root).resolve()),
        "SLAVE": str(args.slave),
    }

    write_text(output_dir / "Makefile", render(TOP_MAKEFILE, mapping))
    write_text(
        output_dir / f"{ioc_name}_startup.script",
        render(STARTUP_SCRIPT, mapping),
    )
    write_text(
        output_dir / f"{ioc_name}_parameters.yaml",
        render(PARAMETERS_YAML, mapping),
    )
    write_text(output_dir / "README.md", render(IOC_README, mapping))
    write_text(output_dir / "src" / "Makefile", render(SRC_MAKEFILE, mapping))
    write_text(
        output_dir / "src" / f"{args.program}.st",
        render(ST_SOURCE, mapping),
    )

    print(f"Created IOC scaffold in {output_dir}")


if __name__ == "__main__":
    try:
        main()
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
