#!/usr/bin/env python3

import argparse
import pathlib


def parse_args():
    parser = argparse.ArgumentParser(
        description="Bundle multiple ST source files into one generated ST file."
    )
    parser.add_argument("--output", required=True, help="Bundled ST output path")
    parser.add_argument("inputs", nargs="+", help="Ordered ST input files")
    return parser.parse_args()


def main():
    args = parse_args()
    output_path = pathlib.Path(args.output)
    input_paths = [pathlib.Path(item) for item in args.inputs]

    output_path.parent.mkdir(parents=True, exist_ok=True)

    parts = [
        "(* Auto-generated by strucpp_bundle_st.py. *)",
        "",
    ]

    for path in input_paths:
        parts.append(f"(* BEGIN {path.name} *)")
        parts.append(path.read_text(encoding="utf-8").rstrip())
        parts.append(f"(* END {path.name} *)")
        parts.append("")

    output_path.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()
