#!/usr/bin/env python3

import argparse
import pathlib
import sys

BEGIN_MARKER = "# --- BEGIN AUTO-GENERATED STRUCPP SUBSTITUTIONS ---"
END_MARKER = "# --- END AUTO-GENERATED STRUCPP SUBSTITUTIONS ---"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate IOC-level <IOC>_all.subs from plugin core and app substitutions."
    )
    parser.add_argument("--output", required=True, help="Output <IOC>_all.subs file")
    parser.add_argument(
        "--input",
        action="append",
        default=[],
        help="Input substitutions file to merge. Can be repeated.",
    )
    parser.add_argument(
        "--prefix",
        default="$(IOC):",
        help="Literal PV prefix to inject into substitutions, default $(IOC):",
    )
    parser.add_argument(
        "--port",
        default="PLUGIN.STRUCPP0",
        help="Literal asyn port name to inject, default PLUGIN.STRUCPP0",
    )
    return parser.parse_args()


def normalize_substitutions(text: str, prefix: str, port: str):
    return text.replace("$(P=)", prefix).replace("$(PORT=PLUGIN.STRUCPP0)", port)


def main():
    args = parse_args()
    output_path = pathlib.Path(args.output)
    input_paths = [pathlib.Path(value) for value in args.input]

    block_lines = [
        BEGIN_MARKER,
        "# Auto-generated by strucpp_ioc_all_subsgen.py",
        "# This block is intended to be auto-loaded by the IOC infrastructure.",
        "",
    ]

    first = True
    for input_path in input_paths:
        if not input_path.exists():
          raise RuntimeError(f"Missing substitutions input: {input_path}")
        text = normalize_substitutions(
            input_path.read_text(encoding="utf-8"),
            args.prefix,
            args.port,
        ).strip()
        if not text:
            continue
        if not first:
            block_lines.append("")
        first = False
        block_lines.append(f"# Begin {input_path.name}")
        block_lines.append(text)
        block_lines.append(f"# End {input_path.name}")

    block_lines.append(END_MARKER)
    generated_block = "\n".join(block_lines) + "\n"

    existing_text = ""
    if output_path.exists():
        existing_text = output_path.read_text(encoding="utf-8")

    if BEGIN_MARKER in existing_text and END_MARKER in existing_text:
        start = existing_text.index(BEGIN_MARKER)
        end = existing_text.index(END_MARKER) + len(END_MARKER)
        if end < len(existing_text) and existing_text[end:end + 1] == "\n":
            end += 1
        updated_text = existing_text[:start].rstrip()
        if updated_text:
            updated_text += "\n\n"
        updated_text += generated_block
    elif existing_text.strip():
        updated_text = existing_text.rstrip() + "\n\n" + generated_block
    else:
        updated_text = generated_block

    output_path.write_text(updated_text, encoding="utf-8")


if __name__ == "__main__":
    try:
        main()
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
